reference_target_config:
  query_url: 'http://localhost:9090'

test_target_config:
  query_url: 'http://localhost:5080/api/default/prometheus'
  basic_auth_user: 'root@example.com'
  basic_auth_pass: 'Complexpass#123'

query_tweaks:
  - note: 'Openobserve is sometimes off by 1ms when parsing floating point start/end timestamps.'
    truncate_timestamps_to_ms: 1000
  - note: 'Openobserve fractional tolerance amount for <agg>_over_time queries'
    adjust_value_tolerance:
      fraction: 0.1

